# Generated by Django 3.1.7 on 2021-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignee_id', models.IntegerField(default=None, null=True)),
                ('submitter_id', models.IntegerField(default=None, null=True)),
                ('requester_id', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('due_at', models.DateTimeField(default=None, null=True)),
                ('priority', models.CharField(default=None, max_length=20, null=True)),
                ('status', models.CharField(default=None, max_length=20, null=True)),
                ('subject', models.CharField(default=None, max_length=200, null=True)),
                ('type', models.CharField(default=None, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
